### ISSUE TITLE
Solve dependency tangle in `substrate-proxy` branch.

### ISSUE THREAD

**Issue by bddap** [docknetwork/substrate-warmup#5]
There is a feature branch in on one of our repos

`git clone -b substrate-proxy git@github.com:docknetwork/substrate-warmup.git`

The substrate-proxy branch attempts to organize crates from the substrate workspace into one super-crate called 'substrate'.

Currently, substrate imports look like:

```
[dependencies.substrate-transaction-pool]
git = "https://github.com/paritytech/substrate.git"
rev = "870b976bec729aaf26cc237df9fd764b8f7b9d7e"
default-features = false

# repeated for every substrate module...

[features]
default = ["std"]
std = [
	"substrate-transaction-pool/std",
	...
]
```

The goal is for them to look like this:

```
[dependencies.substrate]
path = "../substrate-proxy"
default-features = false

[features]
default = ["std"]
std = [
	"substrate/std",
]
```

The feature branch is halfway complete, but I've become stumped on a set of 25 rustc errors.

## To reproduce

See readme for setup. Checkout the branch and run `cargo check`.

**Comment by bddap** [comment]
There is talk of a pending re-organisation of the [substrate repo](https://github.com/paritytech/substrate). That, coupled with the feeling this issue is a dead end, causes me to lean toward closing the issue. @Pauan, any objections?

**Comment by Pauan** [comment]
@bddap Hey, sorry for the delay on this, yeah that sounds fine to me.

I had done a lot of digging into this, but I ran into a lot of weird stuff with `std` (in particular, even when I activated the `std` feature it seemed to have no effect).

I think the idea of combining things is good, but I think we should do it one crate at a time, so it will make the transition easier.
